dubbo:
   application:
      id: dubbo-demo-provider
      name: dubbo-demo-provider
   protocol:
      id: dubbo
      name: dubbo
      port: 12345
   scan:
      basePackages: com.bulain.dubbo.service
   registry:
      id: consul-registry
      address: consul://127.0.0.1:8500
