server:
  port: 8081
dubbo:
   application:
      id: dubbo-demo-consumer
      name: dubbo-demo-consumer
   protocol:
      id: dubbo
      name: dubbo
   registry:
      id: consul-registry
      address: consul://127.0.0.1:8500