server:
  port: 8081
dubbo:
   application:
      id: spring-dubbo-consumer
      name: spring-dubbo-consumer
   registry:
      id: consul-registry
      address: consul://127.0.0.1:8500
   metadata-report:
      address: consul://127.0.0.1:8500
