server:
  port: 8081
dubbo:
   application:
      id: spring-dubbo-consumer
      name: spring-dubbo-consumer
   registry:
      address: zookeeper://127.0.0.1:2181
      simplified: true
#   metadata-report:
#      address: consul://127.0.0.1:8500
